<h1>The Importance of Comfort</h1>
<p>The main objective of your meditation posture should be comfort.  While this may seem obvious to most people, there is at least a substantial number of practitioners who begin their experience with meditation with a mindset of perseverance.  They believe that learning to sit for long periods of time will require them to endure discomfort.  Perhaps they think that learning to endure soreness and discomfort is an important part of training the mind.  Or perhaps they believe that the body just needs to be conditioned, the muscles in the back strengthened, before comfort can be attained.  </p>
<p>In my experience, starting out with the attitude of perseverance was not very helpful.  Usually, pain was a signal that I was doing something wrong with my posture, and by ignoring the pain I only caused a lot of distraction and, no surprise, more pain.  Ignoring discomfort can lead to chronic problems, like inflammation, tendonitis, muscle cramping, loss of mobility, and vulnerability to injury.  Postural discomfort has almost always been a persistent and significant disruption in my ability to focus and relax, a signal that something is awry.  </p>
<p>There are, of course, other types of discomfort that one can safely ignore for a while: an itch here or there, an annoying noise, a cold temperature, or even muscular pain not associated with posture.  But pain resulting from an imbalanced sitting posture is almost always counterproductive for one's practice and damaging to one's overall health.  As a result, I would encourage you to endeavor at all times to be comfortable while sitting for meditation.  To the extent that the advice in this guide results in making you uncomfortable, please do whatever is necessary to make the necessary adjustments and place yourself in a relaxing and sustainable position.</p>
<h1>Preparing to Sit</h1>
<p>You do not have to become an athlete or an advance yogi to sit upright without back support for prolonged periods of time.  A person with a fairly sedentary lifestyle, average muscle tone, and limited flexibility can place themselves in a well-formed posture that should be sustainable for an hour or more.  Nevertheless, comprehensive physical conditioning and yoga are quite helpful to the aspiring meditator.  Virtually all of the meditation postures apart from sitting in a chair require some degree of flexibility and some basic level of muscular strength.  Establishing a fit and healthy body facilitates the development of good meditation posture. </p>
<p>I highly recommend developing a stretching routine that works well for your body, even just five to ten minutes per day.  In this area, there is a great deal of room for personalization.  Some people will have tight hamstrings; others might have tight quads.  Still others might need to work on opening their hips.  Nevertheless, there are several stretches that are generally beneficial.</p>
<h2>Specific Exercises</h2>
<p>The Pigeon Stretch.  This yoga posture, called Kapotasana in Sanskrit, is extremely valuable for those wishing to sit in the lotus posture (or half lotus) without doing harm to the knees.  It can also be useful for anyone who has trouble getting into a cross-legged posture.  I recommend doing pigeon on both sides every day before meditating.  Before a twenty minute meditation session, I will usually spend at least five to ten minutes opening the hips, most of which is spent in some form of pigeon.  There are numerous variations on this stretch, and it is worthwhile to experiment with as many of them as possible.</p>
<p>Shoelace Pose.  Another yoga pose, gomukhasana in Sanskrit, is commonly referred to as “shoelace” pose, or sometimes “cow face” pose (the literal translation).  This stretch is an excellent complement to pigeon, because it directly addresses some of the tissue the hip that pigeon doesn't quite reach as well.</p>
<p>The Doorway Stretch.  This stretch is performed by standing in an open doorway and placing the forearms on either side of the frame.  Lean into the doorway to push the arms back and open the shoulders, stretching the pectoral muscles.  For people who have rounded shoulders or “thoracic kyphosis”, or people who experience cramping between the shoulder blades while sitting, this stretch can make the upper back more comfortable.  There are also numerous “chest openers” in the practice of yoga, any of which may prove helpful to someone who wants to sit comfortably while meditating.</p>
<p>Kettle bell Swings.  Doing swings with a kettle bell strengthens the key muscles that support the body when sitting upright.  Kettle bells can provide many of the benefits of heavy weight-lifting, but with significantly less weight.  Kettle bells are relatively cheap, and can be used at home.  The one disadvantage I have noticed from working with kettle bells is that they can generate some stiffness in the hips, which must otherwise remain flexible for sitting cross-legged.  This can be mitigated by the regular stretching recommended above.</p>
<p>These exercises should greatly help the vast majority of practitioners.  After five years of consistent meditation practice, I still do all three of the above exercises on a regular basis: pigeon every morning for about five minutes before I sit on my cushion, the doorway stretch and kettle bell swings two or three times per week.  However, you should develop the mobility and fitness routine that works best for you.</p>
<h2>A Note on Stretching</h2>
<p>One last note on stretching.  Personally, I find the term “stretching” somewhat misleading.  It evokes the image of physically pulling tissues apart, like pulling on a rubber band, or pulling on a piece of rawhide to stretch and elongate the material.  Your muscles should not be forcefully pulled into a longer position than is uncomfortable.</p>
<p>Instead, think of mobility exercises as teaching your muscles to relax and lengthen.  This is done by extending the muscle to the limit of its range, until you feel a slight sensation of resistance.  You then direct your attention to the muscle to relax it to further to increase its range of motion.  As the muscle relaxes, the feeling of resistance will fade.  You can then deepen the stretch by moving into the increased range of motion until the slight sensation of resistance reappears.  Continue relaxing the muscle and deepening the stretch.iii</p>
<p>It may be helpful when stretching to visualize warm light flowing into the muscle.  This little visualization trick can be helpful in getting the muscle to relax.  After some practice, you won't even need to visualize, you will be able to intentionally relax the muscle just by feel.  Be as gentle as possible at first.  In due time, you will be able to increase the amount of pressure, and you will have an intuitive sense of when to apply more pressure and when to back off.</p>
<h1>The Lower Body</h1>
<p>The starting point to establishing a good meditation posture is figuring out how to arrange the legs.  This will be determined in part by what type of seating you have available.  How you arrange the legs affects what type of seating you choose and vice versa.</p>
<h2>Sitting in a Chair</h2>
<p>One of the most familiar ways of sitting, which people seem to underrate in the world of meditation, is sitting in a chair.  The chair is a valuable invention; its effect on human comfort and productivity has been pervasive.  However, the chair is also a distinctly Western innovation, and many cultures around the world still function largely without it.iv</p>
<p>Reclining in a chair for meditation is a little bit different than sitting in a chair to eat or work.  For one thing, when eating, working, or watching television, your attention is captured by some activity or stimulus.  In addition, you also have the option of fidgeting, squirming, moving around, and making minor adjustments here and there to redistribute your weight over time.  As a result, when sitting in a chair for some activity or entertainment, minor discomforts may linger at the periphery of awareness, if they are even noticeable at all, and are relatively easy to manage.  When meditating, however, you want to sit very still, and a minor discomfort can become a significant aggravation.  </p>
<p>Also, when meditating, reclining with the back against a straight or hard rest tends to be a little uncomfortable.  This may seem counter-intuitive, but it is actually more comfortable to sit up straight without the use of a rest.  This will be explained in more detail below when discussing the upper body.  However, for now, it is sufficient to note that, when sitting in a chair for meditation, it is better to sit toward the front part of the seat.</p>
<p>We are generally advised to keep the legs at 90 degrees when sitting in a chair.  This may be good advice for sitting for long periods of time for productive work while using the back rest.  But it's not the optimal way to arrange the legs for meditation.  Instead, the thighs should be allowed to slope downward, so that the knees are below the hips.  In order to make this possible, you may find it helpful to turn the thighs outward, and allow your feet to turn on their side.   You may even want to cross your ankles.</p>
<p>At this point, I must recommend Esther Gokhale's wonderful book “8 Steps to a Pain Free Back.”  Ms. Gokhale has written a thorough guide on posture in all aspects of daily life.  In her chapter entitled “Stacksitting”, she gives a detailed explanation of how to sit comfortably in a chair without back support, and she provides detailed photographs and illustrations.</p>
<h2>Seiza</h2>
<p>Another way to sit for meditation is kneeling on the floor.  The common term for this is “seiza”, a Japanese term for a formal way of sitting.  This may sound uncomfortable for the knees, but there are several ways to reduce and even eliminate that discomfort.  You can place thick zafu between the legs, so that the weight of the body is supported by the cushion rather than the legs alone.  Or you can buy a seize bench, a small wooden stool that supports the entire weight of the upper body.  Obviously, sitting in seiza requires some degree of flexibility in the thighs.  </p>
<p>Seiza is an excellent position for beginning meditators, because it promotes healthy spinal alignment.  When sitting in seiza, good alignment of the lower back occurs without effort, almost as if automatically.  Most people who start sitting in seize use a cushion between their legs to take some of the pressure off their knees and feet.  Alternatively, they use a seiza bench.</p>
<p>There are several disadvantages to seiza.  For those who not accustomed to it, seiza can impose some strain on the knees and on the tendons at the front the ankle.  It also doesn't provide the best platform for resting the hands.  Personally, I find that my hands always want to slide down my thighs, which tends to pull my shoulders forward and down.  This makes seiza less comfortable than some other positions that I prefer.  Other people may not have this issue.</p>
<h2>Cross-legged</h2>
<p>This is the standard, familiar position for sitting on the ground.  The benefit of sitting in cross-legged position is that it requires relatively little flexibility and places the weight of the body directly over the pelvis and hips.  The disadvantage of sitting cross-legged is that it elevates the knees higher than the hips.  This tips your weight backwards, requiring you to lean forward to maintain your balance, which in turn collapses the lower back and brings the shoulders slumping forward.  This can be comfortable for a short time, but it will cause nagging fatigue.  </p>
<p>The cross-legged posture can nevertheless be a viable position for meditation.  The key is to use a cushion to elevate the hips enough to support the natural curvature of the lumbar spine.  The general rule is that the hips should be higher than the knees.  </p>
<h2>Burmese</h2>
<p>The Burmese posture is similar to sitting cross-legged, except that the knees are positioned more outward so that the legs do not actually intersect.  Instead, the feet are placed one in front of the other.  The shins rest on the floor.  </p>
<p>Burmese requires quite a bit of flexibility in the quadriceps, and places a little more weight on the knees.  A person sitting in Burmese still needs to elevate their hips to raise them above the feet and knees, which requires a little bit higher cushion.  As a result, Burmese can feel a little wobbly, a little less stable than the various forms of lotus.  </p>
<p>The Burmese position has the advantage over cross-legged in that it brings shins down to the floor, providing some added stability.  Some meditation teachers will tell students to have both knees on the floor, forming a tripod-like structure.  This is useful advice, but it is actually the shins that will rest on the floor.  The front of the knee joint point toward the floor, but only if the cushion supporting the buttocks is high enough.</p>
<p>Burmese has the slight disadvantage of being a somewhat wide posture, especially if you have long legs.  This can be a little bothersome in a meditation hall where people are sitting on either side of you.  </p>
<p>I personally find it easy to over-arch the back in Burmese.  Nevertheless, Burmese is a good, comfortable position, which does not demand quite as much hip flexibility as lotus.  If you have trouble getting one (or both) of your knees all the way to the floor, you can place a cushion under the knee to take pressure off that leg.  Most online retailers that sell meditation supplies sell a variety of inexpensive support cushions for just this purpose.</p>
<h2>Quarter Lotus</h2>
<p>Similar to cross-legged, but instead of crossing the legs at the shins, one foot is placed on top of the opposite calf.  This may bring a knee up off the floor, which is fine, because the shin of the top leg rests on the shin of the bottom leg.  One can place both knees on the floor by sitting on a higher cushion.</p>
<p>Quarter lotus is a very comfortable position for people who have the requisite hip flexibility.  I generally find that, when sitting on a lower cushion, I am more comfortable in quarter lotus than in Burmese.  Many long-term practitioners favor quarter lotus as their mainstay sitting position.  In fact, quarter lotus closely resembles the yoga posture called siddhasana or “perfect seat”.  In fact, a classic fifteenth-century manual on hatha yoga, the Hatha Yoga Pradipika, raises the following question: “When siddhasana is mastered, of what use are the various other postures?”v  </p>
<h2>Half Lotus</h2>
<p>Half lotus is similar to quarter lotus, but instead of placing to top foot on the opposite calf, the foot is placed on the thigh.  Half lotus requires more hip flexibility, and also demands considerably flexibility from the feet.  It is normal, when first sitting in this position, to find that the top foot feels very “stretched out” after the session.  This sensation should pass with time, and eventually the feet become quite comfortable.  It is helpful to alternate sides, sitting for one session with the right foot on top, then for the next session with the left on top.</p>
<p>One can sit in a “low” half lotus, where the foot rests on the lower thigh, or a “high” half lotus where the foot rests on the upper thigh, closer to the crease of the hip.  Generally, I find that the low half lotus is more even and comfortable.  A high half lotus tends to extend the gluteal muscles on the hip of the top leg, which means I have less padding on that side of my backside.  This can cause me to lean slightly to one side.</p>
<p>The bottom foot can rest under the knee of the opposite leg, which means that one knee will be off the floor.  Alternatively, I generally like to tuck the bottom foot back under the top thigh, right near the front edge of my cushion, in the space between the thigh and the floor.  This allows both knees to rest on the floor, and allows me to sit on a  slightly lower cushion while preserving the curvature in my lower back.</p>
<h2>Full Lotus</h2>
<p>Full lotus is perhaps the most difficult meditation position for lay practitioners to attain.  Unless one is sitting consistently for substantial periods of time every day, and/or doing consistent yoga to open the hips, it is difficult to maintain the level of flexibility necessary for sitting in full lotus for any length of time.  Even someone who can easily position themselves in lotus will be uncomfortable remaining there for ten or twenty minutes at a time, much less for an hour.  Nevertheless, no discussion of meditation posture would be complete without a discussion of this historic and iconic way of folding the legs.</p>
<p>In full lotus, the legs are crossed at the shins with the feet placed on top of the thighs.  The advantage of full lotus is that it raises the feet above the thighs, which allows the knees and thighs to rest directly on the ground.  This means that very little elevation is needed to raise the seat and hips above the knees.  As a result, full lotus feels compact and solid to those who are acclimated to sitting that way.  Sitting on a lower cushion also allows the hands to rest more easily and securely in the lap, again improving the solidity of the posture.  Full lotus is favored by zen monks, who sit in meditation for long hours each day.</p>
<p>There is also something beautiful about full lotus.  The way the legs fold and intersect has a certain elegant symmetry, and the arrangement of the hips and feet is a visible symbol of the practitioner's commitment to the art of meditation.  </p>
<p>Nevertheless, there are thousands of long-term meditation practitioners who cannot sit in full lotus, or have no particular desire to make the attempt.  There are also dancers and hatha yoga practitioners who can sit in half-lotus with little difficulty, but who rarely practice sustained sitting meditation for more than a few minutes.  For someone who is new to the practice of meditation trying to sit in full lotus is not necessary.  Rather, it is more likely to be a distraction and obstacle to the enjoyment of their practice, if not a cause of injury.  The important thing is to find a way of arranging the legs that works for the individual practitioner.  Over time, it may be possible to develop the ability to sit comfortable in various forms of lotus.  However, one should avoid the notion that there are more or less advanced sitting postures.  The advanced sitting posture is the one that allows you to find comfort and minimize distraction.  </p>
<h2>Mixing it Up</h2>
<p>It may helpful for you to cycle choose two or three of the above options and to cycle through them, sitting in one posture for a session, and then another posture for the next session, and so on.  Over time, you may develop a favorite posture that becomes your main option, or you may find it helpful to continue rotating between a few.  </p>
<p>There are only two rules.  The first rule is, make yourself comfortable.  If a particular way or arranging the legs just isn't working, try some other options until you find a comfortable alternative.  The second rule is, be persistent.  Keep making adjustments until you find the right arrangement for you.  These rules are in order of priority.  Comfort is the lodestone; persistence is founded on your determination to become comfortable in your practice.</p>
<h1>The Upper Body</h1>
<h2>Forward Pelvic Tilt</h2>
<p>Regardless of how the legs are positioned, the most important element of meditation posture is forward pelvic tilt. vi vii viii ix x  The knees should be positioned a little below the hips, creating room for the pelvis to tilt forward.  This brings the belly out and forward and creates some natural, healthy arch in the lower back.  Without this forward pelvic tilt, comfort on a seat (without a back prop) is very difficult. </p>
<p>The purpose of sitting on a cushion or other support during meditation is to achieve and maintain forward pelvic tilt.  By sitting on the front of the cushion, we position ourselves on an inclined plane or a wedge that holds the back of the pelvis higher than the front.  Some modern cushions are actually designed in a wedge shape to directly facilitate forward pelvic tilt. </p>
<p>This is perhaps the little secret of sitting for long periods of time without a back prop.  In essence, the meditation cushion is back support.  By lifting the seat and propping the pelvis forward position, the cushion holds the lower spine in a lordotic (forward) curve.  When one is positioned correctly on a cushion, it actually becomes somewhat of a challenge to round the lower back.  This in turn supports the rest of the back and the shoulders.</p>
<p>This is the reason why we are advised to sit on the forward portion of the cushion.  Sitting toward the back of the cushion would be counterproductive, because it would cause the lower back to round.  Sitting in the middle of the cushion raises the body off the floor, provides a soft surface, and makes room for the legs, but it doesn't support the lower back by pushing the pelvis forward.  It also has a tendency to tilt you forward, and to cause the back to “sway” or “overarch”, or to arch up too high toward the middle back.  Sitting toward the front of the cushion, on the other hand, brings the upper body upright and pushes the lumbar arch lower toward the tailbone.  This eliminates tension in the mid back and subtly brings the chest and head into better alignment over the hips. </p>
<p>One last note about pelvic tilt: some posture coaches and writers will tell you to tilt your pelvis forward until your wait is over your “sitz bones”.  Personally, I have found this instruction, while not wrong, rather confusing.  The reason is because there is a fairly significant range of different positions that will place your weight over the bones of the lower pelvis, to one degree or another.  In addition, depending on the firmness and shape of the cushion, it may become difficult to perceive exactly whether your weight is over your sitz bones or not.  Finally, the sitz bones are connected to other pelvic bones, and it can be hard to distinguish between them, to know exactly where the pelvic bones should make contact.</p>
<p>The forward pelvic tilt should be firm, but not forceful.</p>
<h2>Extended Back</h2>
<p>The second key element to a comfortable meditation posture is an extended back. xi xii xiii  This was an element of meditation posture that eluded me for many years.  However, once I learned how to extend my back, I become dramatically more comfortable while sitting.  Without an extended back I could only sit for a few minutes without discomfort and ultimately cramping in the mid-back.  With an extended back, I can sit comfortably for hours.</p>
<p>Extending the back means relaxing the chest downward.  This may seem contrary the instructions that are given by some meditation teachers.  There is a trend in meditation posture instruction to tell the students to “open the chest” or “open the heart”, or even to gently lift the chest.  These instructions are well meaning but subtly misleading.  Without slumping, the chest must be relaxed  downward and inward.</p>
<p>The instruction to “open the chest” is not necessarily wrong.  It can be a helpful cue to roll back the shoulders, which creates a sense of openness in the chest (more on the shoulders in the next section).  However, many students, when being told to “open the chest”, will actually lift the chest upward rather than rolling the shoulders back.  This lifting of the chest upward is a common mistake that causes a lot of tension in the middle back.  Lifting the chest can also distort or impinge on the small valve at the entrance of the stomach, resulting in acid reflux and heartburn.xiv</p>
<p>Instead of lifting the chest and puffing it forward, one should instead allow the chest to relax downward, not in an exaggerated way, not by slumping, but just by letting it gently release down.  This allows the muscles of the lower and middle back to relax.</p>
<p>There are a few different exercises or cues for feeling the sensation of a relaxed chest and extended back.  Perhaps the easiest exercise is to place your fingers on the base of your xiphoid process, the small bone at the base of your sternum.  Feel the sternum raise as you lift your chest and lower as you relax it down.  When the chest is relaxed, the xiphoid process tucks slightly inward.</p>
<p>Another exercise for getting a feel for relaxing the chest is to lift your arms overhead and reach for the ceiling.  Feel the sensation of the back elongating as you reach upward.  Then, while keeping the back in that position, put the arms down.</p>
<p>Another mental cue to use is to feel yourself “thickening” through the waist.  As the chest relaxed downward the muscles of the mid and lower back seem to widen outward and to thicken like the base of a tree, which must have the strength to support the weight of the branches and crown.</p>
<p>Another feeling to look for is the shape of your lower-to-mid back.  As you lift the chest, the lower-to-mid back will seem to tighten and elongate upward as it squeezes forward.  As you lower the chest, the lower-to-mid back loosen and widen outward.  </p>
<p>Another way to feel this adjustment is, if you are sitting on your seat with forward pelvic tilt, you will notice that you have some “arch” in your lower back.  As you lower the chest, this will reduce the amount of the arch and will move it down your back toward the very bottom of the spine.  The curvature will be shorter and more concentrated near the tailbone.</p>
<p>Finally, while sitting with an anteverted pelvis, you can try reaching with your arms overhead.  Try to reach as high as you can.  You will probably instinctively raise your chest.  Now, with your arms overhead, try to rotate your rib cage forward, and see if you can get your fingers just an inch or two higher.  If you can feel just a little extra reach, then you should have successfully have lowered your chest without slumping.xv  This will result in an extended spine, and a relaxed back.  You can also try this reaching exercise while lying on the floor, just to get a feel for the extension of the spine.</p>
<h2>Open, Relaxed Shoulders</h2>
<p>The third key element of good meditation posture is to have open, relaxed shoulders.  This may seem difficult at first, because your shoulders may want to naturally round forward.  However, if the muscles of the chest are sufficiently relaxed, the shoulders will remain back.  </p>
<p>The important thing to understand here, is that the shoulder can and should open without lifting the chest.  This is one of the most common mistakes for beginning practitioners.  In order to bring the shoulders back, they will lift the chest up.  This does have the effect of rotating the shoulders back and it does produce the appearance to good posture.  However, it does not actually solve the underlying problem of slumped shoulders.</p>
<p>In order to bring the shoulders back, one should do a shoulder roll.  Lift the shoulders up, pull them back, and let them settle down.  Do all of this without lifting the chest.  Do not pull the shoulders down.  Do not try to hold the shoulders back.  Just let them rest in an open position.  It may take some time to get a feel for this, and the difference between slumped and open shoulders can feel quite subtle.  However, it does facilitate a more comfortable meditation posture.</p>
<p>It may be difficult at first to open the shoulders if the chest muscles are tight.  For this reason, I highly recommend doing the doorway stretch (see “Physical Conditioning”) every day until the chest becomes more open.  Thereafter, it may be helpful to do the doorway stretch periodically for maintenance.</p>
<p>One mistake to avoid is pulling the shoulders back and holding them back with effort.  For some people, particularly if their chest muscles are tight, this may seem like the only way to keep the shoulders back.  However, it is better to let the shoulders round than to hold them back with tension.  Instead of holding the shoulders back, one should focus on stretching out the chest.  In addition, it may be necessary to establish good alignment in spine before the shoulders can rest in an open position.  If the lower back is rounded then the shoulders will inevitably come forward.</p>
<p>Lastly, the shoulders should not be shrugged upward or pulled down.  They should simply “float” in their place.  Once they are rolled back, let them rest.  </p>
<h2>Hand and Arm Placement</h2>
<p>The arms should hang as close to the body as possible.  The more the arms move away from the torso, the more they place a strain on the muscles of the back.  </p>
<p>There are many different way of positioning the arms.  I'll suggest three of them here.  First, you can place your hands in a “mudra” position in your the lap.  Second, you can  place the hands on the middle of the thighs.  Third, you can hold the hands in a mudra position at or about your navel.  </p>
<p>For those who are unfamiliar, the term “mudra” is Sanskrit for “gesture”.  It simply refers to a position of the hands.  Traditionally, in Hinduism and Buddhism the hands were placed in a position with symbolic significance.  </p>
<p>Probably the most common mudra today is colloquially called the “cosmic mudra”.  You can form the cosmic mudra by placing either hand in your lap facing upward.  Then place the other hand on top of it, also facing upward.  Tough the tips of your thumbs together to form a gentle oval. </p>
<p>It turns out that cosmic mudra is a very comfortable position for the hands over long periods of time, which is probably a key reason for its popularity.  In addition, because the thumbs rest very lightly against one another, this mudra can be a useful indicator of the quality of your posture.  If you find yourself off balance or starting slumping, the first sign of trouble may be a loss of tone or integrity in the shape of the mudra.</p>
<p>Nevertheless, if you the cosmic mudra annoying, you can just lay your hands in your lap, facing up, with one on top of the other.  Or you can just call it “making an oval”.  In this guide, our only concern is with getting comfortable.</p>
<p>I personally prefer to hold my hands just below my belly button in the shape of the cosmic mudra.  I have a fairly long torso and find that laying my hands in my lap pulls my shoulders forward and out of the ideal alignment.  It may seem strange at first to hold the hands in the air unsupported, but there is surprisingly little effort involved.  The biceps can support the weight of the forearms and hands with no difficulty.  And, because the arms are close to the body, there is almost no extra load or strain on the back.  Moreover, because I usually sit in half-lotus, when my hands are in my lap, they are resting on my heel, which is an uneven surface, and thus my hands have a tendency to slide in one direction or another.  Simply holding my hands at my navel keeps my shoulders in line and eliminates the distraction of feeling my hands slide away.</p>
<p>I also find that placing the hands on the thighs tends to be a little uncomfortable.  This is because my hands always feel like they are either too close or too far away.  If they are too close, I end up resting some of my weight on the hands can cause cramping in my shoulders.  If they are too far away, the weight of my arms tends to pull my shoulders down and forward, again causing cramping in the shoulders.  However, I know of many people who are quite comfortable resting their hands on their thighs.</p>
<p>One other item of note: the higher the cushion, the more difficult it will be to rest the hands on the lap.  The lower the cushion, the easier.  On lower cushions, the angle of the legs and torso is closer to ninety degrees, and the hands can settle into the creases of the hip.  For this reason, it is easier to hold the hands in the lap when sitting in, for example, full lotus, as compared with, for another example, the Burmese position.</p>
<h2>Extended Neck</h2>
<p>The neck can be a surprisingly complicated subject.  Some meditation teachers encourage practitioners to sit with their chin tucked in.xvi xvii  Others say that the chin should be neutral, and the eyes forward, so that the head is perfectly balanced on top of the spine.xviii  Some posture experts say that the head will not be balanced unless the chin is slightly down and the crown of the head pointed toward the ceiling.xix  </p>
<p>The general consensus seems to be that when the head is ideally aligned, the chin will be gently tucked.  This avoids two potential mistakes.  First, many practitioners have a tendency to allow the head to drift forward, sticking out in front of the torso.  This actually causes the muscles in the back of the neck to contract to hold the eyes level.  Obviously, this add some stress to the muscles at the base of the head, and some tension in the back as the weight of the head levers forward.  Keeping the chin tucked engages the muscles at the front of the neck and helps prevent this forward drift.  This in turn makes the neck and back more comfortable. </p>
<p>Second, some people what to lift their chin and nose in a proud-looking pose.  This occurs when people are attempting to sit as tall as possible and lengthen through the spine.  Looking down the nose creates an instinctive sense of tallness or height.  The problem with this posture is that it tends to create tension in the back of the neck over time.  Tucking the chin eliminates the problem.</p>
<p>On the other hand, the instruction to tuck the chin can create a different problem, the drooping of the head.  When told to tuck the chin, some enthusiastic students have tendency to roll the head too far forward.  As one might imagine, this also can create some tension in the neck and back. </p>
<p>A common way of trying to encourage a tucked chin, without a drooping head, is to tell students to imagine they have a string attached to the crown of the head, drawing the head up toward the ceiling.  This is perhaps the best instruction a teacher can give when time is very limited for discussing posture, but this instruction can lead people to lift their chest while they are tucking their chin.  In addition, it is possible to tuck the chin too forcefully.</p>
<p>The key with the head and neck is lightly lower the chin and relax.  When the rest of the posture is sound, the head will balance comfortably in a natural position.  </p>
<h2>Vertical Alignment</h2>
<p>Now try this.  Sit on a meditation seat of your choice, and position yourself as described above, with your pelvis tilted forward, chess lowered, shoulders open, hands and arms comfortably arranged, with your neck retracted and chin slightly down.  Now, hinging at your hips, lean slightly forward.  Then lean slightly back and then side to side.  Get a feel for your most vertical alignment.  Notice how, as you lean back, your abdominal muscles engage, and as you lean forward you back muscles engage.  Feel the muscles in your torso regulating tension up and down in response to the position of your chest in relation to your hips.  Search for a comfortable, vertical posture where everything is balanced.  Don't stress out about finding the perfect spot.  Just work your way into a natural, comfortable alignment.  Most likely, this will be just about as straight and vertical as possible.</p>
<p>I am also getting used to the idea that I should have a slight lean forward and my head should be slightly forward.  See Porter p. 241.</p>
<h1>Stating Options</h1>
<p>There are many options in seating, and the option one choses will depend largely on placement of the legs.</p>
<h2>Chair</h2>
<p>Chairs are an excellent way of sitting.  There is a variety of ways to sit comfortably in a chair for meditation.</p>
<h3>Reclining</h3>
<p>One can always sit in a recliner.  This is an important option for people who are elderly or who may have a back injury or other physical problem that prevents sitting up straight.</p>
<h3>The Towel Trick</h3>
<p>What I call the “towel trick” is a great way to convert a chair, effectively, into a meditation cushion.  Start with a chair that has a flat seat and a straight back, like a dining table chair.  Then take a standard bath towel and fold it in half.  Then fold it in half again, and then again and again.  With four folds, the towel should now form a tick pad.  You can place this in the middle of the chair and sit on the front of the pad.  If the pad slides around, you might want to get another towel, fold that three times, and place it on the seat.  Then place the original folded towel on top.  This can be useful way to have a way to sit when your cushion is unavailable.</p>
<h3>Chair with Zafu</h3>
<p>You can also combine a chair with a zafu (a thick cushion designed specifically for sitting and meditation, covered below).  Simply place the zafu on the chair and sit on top of the zafu.  It is helpful to sit toward the front of the zafu to allow the lower back to arch gently forward.</p>
<h3>Other Options with Cushions</h3>
<p>Some people prefer to place the zafu in the small of their back against the back rest.  Other people may use two zafus, one under the legs and another at the small of the back.  </p>
<h3>Specialty Chairs</h3>
<p>There are some specialty chairs that can be very useful for meditation.  Saddle chairs can provide excellent postural support with a variety of fine adjustments.  Kneeling chairs are also an excellent option, allowing a person essentially to sit in seiza with less strain on the knees.</p>
<h2>Seiza Bench</h2>
<p>The existence of the seiza bench is a testament to the popularity to sitting in seiza.  The name pretty much says it all.  It's a small bench for sitting in the seiza position.  </p>
<p>A seiza bench takes most of the weight of the body off the knees and increases the angle formed by the thighs and calves, thereby reducing the amount of quadriceps flexibility necessary for getting comfortable.  It also takes pressure off the tops of the feet.  Seiza benches are widely available for purchase online.  There are tall benches, short benches, folding benches, curved benches, and many other options.  </p>
<h2>Zafu</h2>
<h3>A Quick Introduction</h3>
<p>A zafu is a round cushion for sitting, best known for its use in meditation.  The term “zafu” is Japanese and originally denotes the type of cushion used in Zen temples and meditation centers.  However, zafus are popular today in virtually all traditions of meditation.  For example, it is not uncommon to see zafus in Tibetan and Theravada meditation halls, secular meditation centers, or even Christian meditation retreats and workshops.  </p>
<p>I highly recommend investing in a zafu cushion.  An improvised cushion may be fine for a while (and I will discuss some options below), but it is difficult to replicate the support and comfort of a special-purpose sitting cushion.  Cushions are now widely available online at a relatively modest expense, and even an inexpensive cushion should last for decades.</p>
<h3>Varieties of Zafu</h3>
<p>With the modern popularity of the zafu, there are now many varieties available: all shapes and sizes and types of filling.  Traditionally, zafus were stuffed with reedmace (cattail) down.  Today they are generally stuffed with either kapok (cotton-like material) or buckwheat hulls (the outer caff of buckwheat grains).  </p>
<p>Kapok zafus tend to be thicker, allowing you to sit up higher.  Buckwheat hull zafus tend to be more malleable, and they generally do not compress over time.  Some initial compression may be noticeable as the hulls “settle”, but this can be eliminated by “fluffing” the cushion.  </p>
<p>I'm inclined to recommend the buckwheat hull zafu.  This is the type of cushion I have used for a few years, and it seems to be the most popular.  It is easy to adjust the thickness and firmness of the buckwheat hull zafu by adding or removing some hulls.  As a result, this is a good option for a beginning meditator.  </p>
<p>The kapok zafu is also an excellent choice.  From what I understand, many experienced zen practitioners may prefer kapok for its softness.  That being said, most kapok cushions I have seen on the market are quite thick compared to what I've seen my local zen center.  I'm not sure if this is due to compression over time; from what I understand, kapok does not compress as easily as cotton.  Need to talk to ASZC about this.</p>
<p>There are also more contemporary materials available.  I am aware of a few different sources that sell zafus with memory foam.  However, these tend to be more expensive, and I am uncertain as the advantages.</p>
<h3>Zafu Height</h3>
<p>The size and height of the cushion will depend largely on how the legs are arranged. A person sitting in seiza, using a cushion between the legs, will probably want a larger, fuller cushion. A person sitting cross-legged will want a fairly high cushion.  A person sitting Burmese will want a high or medium height cushion.  A person sitting in quarter lotus will want a medium to low cushion.  A person sitting in half or full lotus may want something quite thin.</p>
<p>Another variable is a person's height.  Taller people tend to prefer higher cushions.  I suspect this is because a longer torso means a longer spinal column, which requires just a little more support in order to maintain its ideal vertical alignment.</p>
<p>In general, a higher cushion will do a better job of providing support for the lower back.  However, once the optimal height has been reached, additional cushion height become superfluous, and only contributes to instability.  In this respect, finding an optimal height for the cushion is one of the first and most important adjustments you can make.</p>
<h3>Adjusting Zafu Height</h3>
<p>A great way to experiment with different cushion heights is to place a folded towel under a buckwheat hull zafu.  My zafu at home, which is just a typical buckwheat hull zafu purchased from a major online vendor, is 5 inches tall (12 centimeters) when smoothed flat (measuring from the floor to the top of front edge of the cushion).  If I fold a towel and place it underneath the cushion, I get 7 inches (17 centimeters) of height.  If I fold a second towel and place it under the first, I get about 9 inches (21 centimeters) of height.  I can further affect the height by fluffing the zafu, which gets me another half inch, or by wiggling my buttocks around to compress the cushion into a wedge shape.  That usually reduces the height of the front size by an inch or two.  </p>
<h3>Using a Zabuton</h3>
<p>A zabuton is a wide rectangular pad that is often used under a zafu to provide comfort for the legs.  A zabuton can be useful on hardwood or tile floors.  It is not necessary to use a zabuton on carpet.  If you are tall and want to use a zabuton, I'd look for an extra-large version, so your knees don't hang off the edges.</p>
<h3>Positioning on the Zafu</h3>
<p>You should sit on the front of the zafu.  There is room for experimentation here.  With a higher zafu, you may sit more toward the center.  With a lower zafu, you may want to sit more toward the front, near the very front edge.  If you sit too far back on the zafu, it will not serve its essential purpose of supporting the natural curvature of your low back.  In addition, sitting too far back may cause the front of the zafu to place pressure on the sciatic nerve of one or both legs.  This may in turn have the effect of putting your lower legs to sleep.  On the other hand, if you sit too far forward, you may start to feel uneven, tilted to one side.  Sitting to far back on the zafu may also have the effect of tilting you too far forward, which can cause your back to “sway” or “overarch”, in other words, to curve too much and too high up into the mid back.</p>
<h3>Improvised Seating</h3>
<p>If for any reason you simply cannot obtain a zafu, or if you are traveling and don't have access to one, there are many ways to improvise a meditation cushion.  Folded blankets are an excellent choice.  Wool blankets are particularly good for this purpose, because they hold their shape well and tend not to compress as much as cotton or soft polyester.  Folded terrycloth towels can also serve as a cushion.  You can stack up some books and cover them with a towel.  You can use a yoga block, or a yoga block and a hand towel folded on top.  You can also sit on the edge of a bed or on the front edge of a chair or couch.  </p>
<h1>Some Common Combinations</h1>
<h3>Option 1: Upright in a Chair</h3>
<p>Find a firm chair with a relatively flat seat and straight back.  Place a folded towel on the seat if necessary to provide some cushion.  Place another folded towel on top of the first to provide some support for your backside, so as to facilitate some anterior pelvic tilt.  Sit toward the front of the chair, and feel the bones of your pelvis, the sitz bones (or just in front of the sitz bones), firmly pressing into the seat.  Align your chest, shoulders, and head as described in “The Upper Body”, above.  Rest your hands on your thighs.</p>
<h3>Option 2: Seiza</h3>
<p>Borrow a seiza bench or buy one online.  Or turn a zafu on its side and place it between your legs.  If using a zafu, sit toward the front of the cushion, and try to position yourself so that your pelvis is tilting forward.  Align your chest, shoulders, and head as described in “The Upper Body”, above.  Rest your hands on your thighs.</p>
<p></p>
<p>If seiza over-stretches the tops of your feet, you might get a zabuton and place your bench or cushion on top.  Then sit so that your feet hang off the back of the zabuton.</p>
<h3>Option 3: Cross-Legged</h3>
<p>Get a high cushion, or get an average-height cushion and raise it with towels.  See “Adjusting Zafu Height” above.  Sit cross-legged toward the front.  Align your chest, shoulders, and head as described in “The Upper Body”, above.  Rest your hands in your lap or on your thighs.</p>
<h3>Option 4: Burmese</h3>
<p>Get a high cushion, or get an average-height cushion and raise it with towels.  See “Adjusting Zafu Height” above.  Sit in Burmese toward the front of the cushion.  Align your chest, shoulders, and head as described in “The Upper Body”, above.  Hold your hands in the cosmic mudra at the level of your abdomen.</p>
<h3>Option 5: Lotus</h3>
<p>Get a lower or medium-height cushion.  Sit in a version of lotus of your choice (quarter, half, or full) toward the front of the cushion.  Align your chest, shoulders, and head as described in “The Upper Body”, above.  Hold your hands in the cosmic mudra at the level of your abdomen or resting in your lap.</p>
<h1>Troubleshooting</h1>
<h3>Pain in the hip flexors</h3>
<p>Get the knees below the hips</p>
<p>Lean more forward</p>
<h2>Pain between the shoulder blades</h2>
<p>Arm placement</p>
<p>Rounding the shoulders</p>
<p>Insufficient pelvic tilt</p>
<h2>Pain in the middle of the back</h2>
<p>Lower the chest</p>
<h2>Pain in the lower back</h2>
<p>More pelvic tilt</p>
<p>Too much pelvic tilt</p>
<p>Lower the chest</p>
<h2>Residual pain in the lower back</h2>
<p>Too much pelvic tilt</p>
<p>Need to acclimate to pelvic tilt</p>
<h2>Legs falling asleep</h2>
<p>Sit more forward on the cushion</p>
<p>Get up and move around</p>
<h2>Headaches</h2>
<p>Relax the neck</p>
<p>Arm placement</p>
<p>Lower the chest</p>
<h2>Heartburn</h2>
<p>Lower the chest</p>
<h2>Drowsiness</h2>
<p>Get some sleep</p>
<p>Sit unsupported</p>
<h2>For Tall People</h2>
<p>Higher cushion</p>
<h2>Pain along the Iliac Crest</h2>
<p>Over-arching, lifting the chest</p>
<h2>Common Questions</h2>
<p>How far back to sit on the cushion</p>
<p>Should the back be straight?</p>
<p>The back should be straight.  This means no slumping.  Pelvis tilted forward, chest relaxed, shoulders rotated back and relaxed.</p>
<p>Should the spine be straight like a stack of coins?</p>
<p>At one time, this was a useful metaphor for teaching people to sit with a straight back.  Today, it is confusing, because the anatomy of the spine is so widely understood, and the vertebrae do not sit straight.</p>
<p>Eyes open or closed?</p>
<p>Should I retract my shoulders?</p>
<p>Should my weight be over my sitz bones?</p>
<p>This can cause over-arching.  Might work well on a chair or bench.  Confusing on a zafu.</p>
