<h1>Arranging the Legs</h1>

<p>The starting point to establishing a good meditation posture is figuring out how to arrange the legs.  This will be determined in part by what type of seating you have available.  How you arrange the legs affects what type of seating you choose and vice versa.</p>

<h2>Sitting in a Chair</h2>

<p>One of the most familiar ways of sitting, which people seem to underrate in the world of meditation, is sitting in a chair.  The chair is a valuable invention; its effect on human comfort and productivity has been pervasive.  However, the chair is also a distinctly Western innovation, and many cultures around the world still function largely without it. (ENDNOTE 4)</p>

<p>Reclining in a chair for meditation is a little bit different than sitting in a chair to eat or work.  For one thing, when eating, working, or watching television, your attention is captured by some activity or stimulus.  In addition, you also have the option of fidgeting, squirming, moving around, and making minor adjustments here and there to redistribute your weight over time.  As a result, when sitting in a chair for some activity or entertainment, minor discomforts may linger at the periphery of awareness, if they are even noticeable at all, and are relatively easy to manage.  When meditating, however, you want to sit very still, and a minor discomfort can become a significant aggravation.</p>

<p>Also, when meditating, reclining with the back against a straight or hard rest tends to be a little uncomfortable.  This may seem counter-intuitive, but it is actually more comfortable to sit up straight without the use of a rest.  This will be explained in more detail below when discussing the upper body.  However, for now, it is sufficient to note that, when sitting in a chair for meditation, it is better to sit toward the front part of the seat.</p>

<p>We are generally advised to keep the legs at 90 degrees when sitting in a chair.  This may be good advice for sitting for long periods of time for productive work while using the back rest.  But it's not the optimal way to arrange the legs for meditation.  Instead, the thighs should be allowed to slope downward, so that the knees are below the hips.  In order to make this possible, you may find it helpful to turn the thighs outward, and allow your feet to turn on their side.   You may even want to cross your ankles.</p>

<p>At this point, I must recommend Esther Gokhale's wonderful book “8 Steps to a Pain Free Back.”  Ms. Gokhale has written a thorough guide on posture in all aspects of daily life.  In her chapter entitled “Stacksitting”, she gives a detailed explanation of how to sit comfortably in a chair without back support, and she provides detailed photographs and illustrations.</p>

<h2>Seiza</h2>

<p>Another way to sit for meditation is kneeling on the floor.  The common term for this is “seiza”, a Japanese term for a formal way of sitting.  This may sound uncomfortable for the knees, but there are several ways to reduce and even eliminate that discomfort.  You can place thick zafu between the legs, so that the weight of the body is supported by the cushion rather than the legs alone.  Or you can buy a seize bench, a small wooden stool that supports the entire weight of the upper body.  Obviously, sitting in seiza requires some degree of flexibility in the thighs.  </p>
<p>Seiza is an excellent position for beginning meditators, because it promotes healthy spinal alignment.  When sitting in seiza, good alignment of the lower back occurs without effort, almost as if automatically.  Most people who start sitting in seize use a cushion between their legs to take some of the pressure off their knees and feet.  Alternatively, they use a seiza bench.</p>
<p>There are several disadvantages to seiza.  For those who not accustomed to it, seiza can impose some strain on the knees and on the tendons at the front the ankle.  It also doesn't provide the best platform for resting the hands.  Personally, I find that my hands always want to slide down my thighs, which tends to pull my shoulders forward and down.  This makes seiza less comfortable than some other positions that I prefer.  Other people may not have this issue.</p>
<h2>Cross-legged</h2>
<p>This is the standard, familiar position for sitting on the ground.  The benefit of sitting in cross-legged position is that it requires relatively little flexibility and places the weight of the body directly over the pelvis and hips.  The disadvantage of sitting cross-legged is that it elevates the knees higher than the hips.  This tips your weight backwards, requiring you to lean forward to maintain your balance, which in turn collapses the lower back and brings the shoulders slumping forward.  This can be comfortable for a short time, but it will cause nagging fatigue.  </p>
<p>The cross-legged posture can nevertheless be a viable position for meditation.  The key is to use a cushion to elevate the hips enough to support the natural curvature of the lumbar spine.  The general rule is that the hips should be higher than the knees.  </p>
<h2>Burmese</h2>
<p>The Burmese posture is similar to sitting cross-legged, except that the knees are positioned more outward so that the legs do not actually intersect.  Instead, the feet are placed one in front of the other.  The shins rest on the floor.  </p>
<p>Burmese requires quite a bit of flexibility in the quadriceps, and places a little more weight on the knees.  A person sitting in Burmese still needs to elevate their hips to raise them above the feet and knees, which requires a little bit higher cushion.  As a result, Burmese can feel a little wobbly, a little less stable than the various forms of lotus.  </p>
<p>The Burmese position has the advantage over cross-legged in that it brings shins down to the floor, providing some added stability.  Some meditation teachers will tell students to have both knees on the floor, forming a tripod-like structure.  This is useful advice, but it is actually the shins that will rest on the floor.  The front of the knee joint point toward the floor, but only if the cushion supporting the buttocks is high enough.</p>
<p>Burmese has the slight disadvantage of being a somewhat wide posture, especially if you have long legs.  This can be a little bothersome in a meditation hall where people are sitting on either side of you.  </p>
<p>I personally find it easy to over-arch the back in Burmese.  Nevertheless, Burmese is a good, comfortable position, which does not demand quite as much hip flexibility as lotus.  If you have trouble getting one (or both) of your knees all the way to the floor, you can place a cushion under the knee to take pressure off that leg.  Most online retailers that sell meditation supplies sell a variety of inexpensive support cushions for just this purpose.</p>
<h2>Quarter Lotus</h2>
<p>Similar to cross-legged, but instead of crossing the legs at the shins, one foot is placed on top of the opposite calf.  This may bring a knee up off the floor, which is fine, because the shin of the top leg rests on the shin of the bottom leg.  One can place both knees on the floor by sitting on a higher cushion.</p>
<p>Quarter lotus is a very comfortable position for people who have the requisite hip flexibility.  I generally find that, when sitting on a lower cushion, I am more comfortable in quarter lotus than in Burmese.  Many long-term practitioners favor quarter lotus as their mainstay sitting position.  In fact, quarter lotus closely resembles the yoga posture called siddhasana or “perfect seat”.  In fact, a classic fifteenth-century manual on hatha yoga, the Hatha Yoga Pradipika, raises the following question: “When siddhasana is mastered, of what use are the various other postures?”v  </p>
<h2>Half Lotus</h2>
<p>Half lotus is similar to quarter lotus, but instead of placing to top foot on the opposite calf, the foot is placed on the thigh.  Half lotus requires more hip flexibility, and also demands considerably flexibility from the feet.  It is normal, when first sitting in this position, to find that the top foot feels very “stretched out” after the session.  This sensation should pass with time, and eventually the feet become quite comfortable.  It is helpful to alternate sides, sitting for one session with the right foot on top, then for the next session with the left on top.</p>
<p>One can sit in a “low” half lotus, where the foot rests on the lower thigh, or a “high” half lotus where the foot rests on the upper thigh, closer to the crease of the hip.  Generally, I find that the low half lotus is more even and comfortable.  A high half lotus tends to extend the gluteal muscles on the hip of the top leg, which means I have less padding on that side of my backside.  This can cause me to lean slightly to one side.</p>
<p>The bottom foot can rest under the knee of the opposite leg, which means that one knee will be off the floor.  Alternatively, I generally like to tuck the bottom foot back under the top thigh, right near the front edge of my cushion, in the space between the thigh and the floor.  This allows both knees to rest on the floor, and allows me to sit on a  slightly lower cushion while preserving the curvature in my lower back.</p>
<h2>Full Lotus</h2>
<p>Full lotus is perhaps the most difficult meditation position for lay practitioners to attain.  Unless one is sitting consistently for substantial periods of time every day, and/or doing consistent yoga to open the hips, it is difficult to maintain the level of flexibility necessary for sitting in full lotus for any length of time.  Even someone who can easily position themselves in lotus will be uncomfortable remaining there for ten or twenty minutes at a time, much less for an hour.  Nevertheless, no discussion of meditation posture would be complete without a discussion of this historic and iconic way of folding the legs.</p>
<p>In full lotus, the legs are crossed at the shins with the feet placed on top of the thighs.  The advantage of full lotus is that it raises the feet above the thighs, which allows the knees and thighs to rest directly on the ground.  This means that very little elevation is needed to raise the seat and hips above the knees.  As a result, full lotus feels compact and solid to those who are acclimated to sitting that way.  Sitting on a lower cushion also allows the hands to rest more easily and securely in the lap, again improving the solidity of the posture.  Full lotus is favored by zen monks, who sit in meditation for long hours each day.</p>
<p>There is also something beautiful about full lotus.  The way the legs fold and intersect has a certain elegant symmetry, and the arrangement of the hips and feet is a visible symbol of the practitioner's commitment to the art of meditation.  </p>
<p>Nevertheless, there are thousands of long-term meditation practitioners who cannot sit in full lotus, or have no particular desire to make the attempt.  There are also dancers and hatha yoga practitioners who can sit in half-lotus with little difficulty, but who rarely practice sustained sitting meditation for more than a few minutes.  For someone who is new to the practice of meditation trying to sit in full lotus is not necessary.  Rather, it is more likely to be a distraction and obstacle to the enjoyment of their practice, if not a cause of injury.  The important thing is to find a way of arranging the legs that works for the individual practitioner.  Over time, it may be possible to develop the ability to sit comfortable in various forms of lotus.  However, one should avoid the notion that there are more or less advanced sitting postures.  The advanced sitting posture is the one that allows you to find comfort and minimize distraction.  </p>
<h2>Mixing it Up</h2>
<p>It may helpful for you to cycle choose two or three of the above options and to cycle through them, sitting in one posture for a session, and then another posture for the next session, and so on.  Over time, you may develop a favorite posture that becomes your main option, or you may find it helpful to continue rotating between a few.  </p>
<p>There are only two rules.  The first rule is, make yourself comfortable.  If a particular way or arranging the legs just isn't working, try some other options until you find a comfortable alternative.  The second rule is, be persistent.  Keep making adjustments until you find the right arrangement for you.  These rules are in order of priority.  Comfort is the lodestone; persistence is founded on your determination to become comfortable in your practice.</p>
