<h2>Extended Neck</h2>
<p>The neck can be a surprisingly complicated subject.  Some meditation teachers encourage practitioners to sit with their chin tucked in.xvi xvii  Others say that the chin should be neutral, and the eyes forward, so that the head is perfectly balanced on top of the spine.xviii  Some posture experts say that the head will not be balanced unless the chin is slightly down and the crown of the head pointed toward the ceiling.xix  </p>
<p>The general consensus seems to be that when the head is ideally aligned, the chin will be gently tucked.  This avoids two potential mistakes.  First, many practitioners have a tendency to allow the head to drift forward, sticking out in front of the torso.  This actually causes the muscles in the back of the neck to contract to hold the eyes level.  Obviously, this add some stress to the muscles at the base of the head, and some tension in the back as the weight of the head levers forward.  Keeping the chin tucked engages the muscles at the front of the neck and helps prevent this forward drift.  This in turn makes the neck and back more comfortable. </p>
<p>Second, some people what to lift their chin and nose in a proud-looking pose.  This occurs when people are attempting to sit as tall as possible and lengthen through the spine.  Looking down the nose creates an instinctive sense of tallness or height.  The problem with this posture is that it tends to create tension in the back of the neck over time.  Tucking the chin eliminates the problem.</p>
<p>On the other hand, the instruction to tuck the chin can create a different problem, the drooping of the head.  When told to tuck the chin, some enthusiastic students have tendency to roll the head too far forward.  As one might imagine, this also can create some tension in the neck and back. </p>
<p>A common way of trying to encourage a tucked chin, without a drooping head, is to tell students to imagine they have a string attached to the crown of the head, drawing the head up toward the ceiling.  This is perhaps the best instruction a teacher can give when time is very limited for discussing posture, but this instruction can lead people to lift their chest while they are tucking their chin.  In addition, it is possible to tuck the chin too forcefully.</p>
<p>The key with the head and neck is lightly lower the chin and relax.  When the rest of the posture is sound, the head will balance comfortably in a natural position.  </p>
<h2>Vertical Alignment</h2>
<p>Now try this.  Sit on a meditation seat of your choice, and position yourself as described above, with your pelvis tilted forward, chess lowered, shoulders open, hands and arms comfortably arranged, with your neck retracted and chin slightly down.  Now, hinging at your hips, lean slightly forward.  Then lean slightly back and then side to side.  Get a feel for your most vertical alignment.  Notice how, as you lean back, your abdominal muscles engage, and as you lean forward you back muscles engage.  Feel the muscles in your torso regulating tension up and down in response to the position of your chest in relation to your hips.  Search for a comfortable, vertical posture where everything is balanced.  Don't stress out about finding the perfect spot.  Just work your way into a natural, comfortable alignment.  Most likely, this will be just about as straight and vertical as possible.</p>
<p>I am also getting used to the idea that I should have a slight lean forward and my head should be slightly forward.  See Porter p. 241.</p>
